trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Self-hosted agent

variables:
  appName: 'MyNextJsApp'
  parentSite: 'Optimus Apps'
  deployPath: 'C:\\inetpub\\wwwroot\\Optimus Apps\\$(appName)'
  siteName: 'Optimus_$(appName)'
  appPoolName: 'AppPool_$(appName)'
  portHttp: 8026
  portHttps: 8025

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    echo Installing dependencies...
    npm install
    echo Cleaning npm cache...
    npm cache clean --force
  displayName: 'Install dependencies'

# Build the Next.js app
- script: |
    echo Building the Next.js app...
    npm run build
    echo Cleaning up cache...
    if exist node_modules\.cache rmdir /s /q node_modules\.cache
    if exist .next\cache rmdir /s /q .next\cache
  displayName: 'Build Next.js app and clean up'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.next'
    artifactName: 'nextjs-app'
    publishLocation: 'Container'

# ✅ Download build artifacts before deployment
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'nextjs-app'
    downloadPath: '$(Build.SourcesDirectory)\artifact'

# ✅ CD - Deploy using external PowerShell script
- task: PowerShell@2
  displayName: 'Deploy to IIS via Script'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)\scripts\deploy-to-iis.ps1'
    arguments: >
      -BuildArtifactPath "$(Build.SourcesDirectory)\artifact\nextjs-app"
      -DeployPath "$(deployPath)"
      -AppPoolName "$(appPoolName)"
      -SiteName "$(siteName)"
      -PortHttp $(portHttp)
      -PortHttps $(portHttps)
    pwsh: false
