trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Self-hosted agent

variables:
  appName: 'MyNextJsApp'
  parentSite: 'Optimus Apps'
  unzipPath: 'C:\\Cicd-frontend'
  deployPath: 'C:\\Cicd-frontend\\$(appName)'
  siteName: 'Optimus_$(appName)'
  appPoolName: 'AppPool_$(appName)'
  portHttp: 8026
  portHttps: 8025
  zipPath: '$(Build.ArtifactStagingDirectory)\nextjs-app.zip'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    echo Installing dependencies...
    npm install
    echo Cleaning npm cache...
    npm cache clean --force
  displayName: 'Install dependencies'

# Build the Next.js app
- script: |
    echo Building the Next.js app...
    npm run build
    echo Cleaning up cache...
    if exist node_modules\.cache rmdir /s /q node_modules\.cache
    if exist .next\cache rmdir /s /q .next\cache
  displayName: 'Build Next.js app and clean up'

# Zip the .next folder
- script: |
    echo Zipping build artifacts...
    powershell Compress-Archive -Path .next\* -DestinationPath "$(zipPath)" -Force
  displayName: 'Zip build artifacts'

# Publish zipped artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(zipPath)'
    artifactName: 'nextjs-app'
    publishLocation: 'Container'
  displayName: 'Publish zipped artifact'

# Download build artifact
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'nextjs-app'
    downloadPath: '$(Build.SourcesDirectory)\artifact'

# CD - Deploy to IIS via external script
- task: PowerShell@2
  displayName: 'Deploy to IIS via Script'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)\scripts\deploy-to-iis.ps1'
    arguments: >
      -ZipFilePath "$(Build.SourcesDirectory)\artifact\nextjs-app\nextjs-app.zip"
      -UnzipPath "$(unzipPath)"
      -DeployPath "$(deployPath)"
      -AppPoolName "$(appPoolName)"
      -SiteName "$(siteName)"
      -PortHttp $(portHttp)
      -PortHttps $(portHttps)
    pwsh: false