trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Self-hosted agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || exit 1
  displayName: 'Install dependencies and build'
  continueOnError: false

- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/.next'
    artifactName: 'nextjs-app'
    publishLocation: 'Container'
