trigger:
  branches:
    include:
      - main

pool:
  name: Default  # <-- Your self-hosted agent name

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    echo Installing dependencies...
    npm install
    echo Cleaning npm cache...
    npm cache clean --force
  displayName: 'Install dependencies'

# Build the Next.js app and clean up
- script: |
    echo Building the Next.js app...
    npm run build
    echo Cleaning up .cache folders...
    if exist node_modules\.cache rmdir /s /q node_modules\.cache
    if exist .next\cache rmdir /s /q .next\cache
  displayName: 'Build Next.js app and clean up'

# Publish build artifacts (keeping only necessary files)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.next'  # Only publish the .next folder if you're using SSR or static export
    artifactName: 'nextjs-app'
    publishLocation: 'Container'

# Clean up exhausted space after the build
- script: |
    echo Cleaning up temporary files...
    REM Remove node_modules and artifact staging directory
    if exist "$(Build.SourcesDirectory)\node_modules" rmdir /s /q "$(Build.SourcesDirectory)\node_modules"
    if exist "$(Build.ArtifactStagingDirectory)" rmdir /s /q "$(Build.ArtifactStagingDirectory)"
  displayName: 'Clean up exhausted space'

# Optional: Docker cleanup (uncomment if needed and Docker is installed)
# - script: docker system prune -f
#   displayName: 'Clean up Docker images'
