trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Self-hosted agent

variables:
  appName: 'MyNextJsApp'
  parentSite: 'Optimus Apps'
  deployPath: 'C:\\inetpub\\wwwroot\\Optimus Apps\\$(appName)'
  siteName: 'Optimus_$(appName)'
  appPoolName: 'AppPool_$(appName)'
  portHttp: 8026
  portHttps: 8025
  artifactFolder: '$(Build.ArtifactStagingDirectory)\nextjs-app'
  zipPath: '$(Build.ArtifactStagingDirectory)\nextjs-app.zip'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    echo Installing dependencies...
    npm install
    echo Cleaning npm cache...
    npm cache clean --force
  displayName: 'Install dependencies'

# Build the Next.js app
- script: |
    echo Building the Next.js app...
    npm run build
    echo Cleaning up cache...
    if exist node_modules\.cache rmdir /s /q node_modules\.cache
    if exist .next\cache rmdir /s /q .next\cache
  displayName: 'Build Next.js app and clean up'

# Zip the .next folder (Windows zip)
- script: |
    echo Zipping build artifacts...
    powershell Compress-Archive -Path .next\* -DestinationPath "$(zipPath)" -Force
  displayName: 'Zip build artifacts'

# Verify artifact contents
- script: |
    echo Listing zipped artifact contents...
    powershell -Command "Expand-Archive -Path '$(zipPath)' -DestinationPath '$(Build.ArtifactStagingDirectory)\unzipped' -Force"
    dir "$(Build.ArtifactStagingDirectory)\unzipped" /s
  displayName: 'Verify artifact contents'

# Publish zipped artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(zipPath)'
    artifactName: 'nextjs-app'
    publishLocation: 'Container'
  displayName: 'Publish zipped artifact'

# Download build artifacts before deployment
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'nextjs-app'
    downloadPath: '$(Build.SourcesDirectory)\artifact'

# Unzip downloaded artifact before deployment
- script: |
    echo Extracting zipped artifact...
    powershell -Command "Expand-Archive -Path '$(Build.SourcesDirectory)\artifact\nextjs-app.zip' -DestinationPath '$(Build.SourcesDirectory)\artifact\nextjs-app' -Force"
  displayName: 'Unzip downloaded artifact'

# CD - Deploy using PowerShell script
- task: PowerShell@2
  displayName: 'Deploy to IIS via Script'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)\scripts\deploy-to-iis.ps1'
    arguments: >
      -BuildArtifactPath "$(Build.SourcesDirectory)\artifact\nextjs-app"
      -DeployPath "$(deployPath)"
      -AppPoolName "$(appPoolName)"
      -SiteName "$(siteName)"
      -PortHttp $(portHttp)
      -PortHttps $(portHttps)
    pwsh: false
