trigger:
  branches:
    include:
      - main

pool:
  name: Default  # <-- IMPORTANT: Your self-hosted agent name
  # Don't use `vmImage: 'ubuntu-latest'` since you are using your own agent.

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build Next.js app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.next'
    artifactName: 'nextjs-app'
    publishLocation: 'Container'